import streamlit as st
from core.router import route_task
from services.groq_service import ask_groq

st.title("Multi-Provider Content Router")

st.write("Generate Images, Videos, or Voice using specialized providers.")

task = st.selectbox(
    "Select Content Type",
    ["Image", "Video", "Voice"]
)

prompt = st.text_area(
    "Enter Prompt",
    placeholder="Example: Modern gym ad creative"
)

quality = st.selectbox(
    "Priority",
    ["Fast", "Balanced", "Premium"]
)

if st.button("Generate Content"):
    provider = route_task(task)

    st.success(f"Request Routed To: {provider}")

    st.code(f"""
POST /api/generate
{{
  "type": "{task.lower()}",
  "prompt": "{prompt}",
  "priority": "{quality.lower()}"
}}
""")

    st.info("Frontend sends one request. Backend routes to best provider.")

    if task == "Image":
        with st.spinner("Groq optimizing image prompt..."):
            enhanced_prompt = ask_groq(
                f"Improve this image generation prompt for marketing creative: {prompt}"
            )

        st.subheader("Groq Enhanced Prompt")
        st.write(enhanced_prompt)

        st.image(
            "https://placehold.co/900x450/png?text=AI+Generated+Image",
            caption="Generated by Image Provider (Replicate / Stability AI)"
        )

    elif task == "Video":
        st.video("https://www.w3schools.com/html/mov_bbb.mp4")

    else:
        st.audio("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3")

    st.json({
        "type": task,
        "provider": provider,
        "status": "completed",
        "saved_to": "workspace_assets/"
    })